#pragma once
#include "Singleton.h"
#include <array>
#include <condition_variable>
#include <chrono>
#include <deque>
#include <map>
#include <memory>
#include <functional>
#include <set>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>
#include <iostream>
#include <mutex>

using namespace std::chrono;
using std::array;
using std::begin;
using std::deque;
using std::end;
using std::function;
using std::make_shared;
using std::make_unique;
using std::map;
using std::multimap;
using std::pair;
using std::set;
using std::shared_ptr;
using std::string;
using std::unique_ptr;
using std::unordered_map;
using std::unordered_multimap;
using std::unordered_set;
using std::vector;
using std::mutex;
using std::condition_variable;
using std::cout;
using std::cerr;
using std::endl;
